title: Yuhao Li Personal Page
description: A personal page for Yuhao Li
theme: just-the-docs

url: https://github.com/chkxw/chkxw.github.io
aux_links:
  Source Code: https://github.com/chkxw/chkxw.github.io

nav_external_links:
  - title: Yuhao Li
    url: https://chkxw.github.io/

color_scheme: dark-blue

callouts:
  hint:
    title: 💡 Hint
    color: grey-md
    opacity: 0.25

  info:
    title: ℹ️ Info
    color: blue
    opacity: 0.2
  
  attention:
    title: ⚠️ Attention
    color: yellow
    opacity: 0.2

  caution:
    title: ❗️ Caution
    color: red
    opacity: 0.15

logo: /assets/images/page_icon_white.png
favicon_ico: /assets/images/page_icon_white.png
